# Generated by Django 4.0.4 on 2022-10-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did_unlock', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pinpadstatus',
            name='unlock',
        ),
        migrations.AddField(
            model_name='pinpadstatus',
            name='password',
            field=models.CharField(default='12345678', max_length=255),
        ),
    ]
